SQL practice on Indian IPO data (MySQL)

In [28]:
import pandas as pd
from sqlalchemy import create_engine, text
from getpass import getpass
from urllib.parse import quote_plus

pw = quote_plus(getpass("MySQL password: "))
engine = create_engine(f"mysql+pymysql://root:{pw}@localhost:3306/ipo_db")

In [29]:
pd.read_sql(text("SELECT COUNT(*) AS n FROM ipos"), engine)

     n
0  509

In [30]:
def run(q):
    return pd.read_sql(text(q), engine)

In [ ]:
# the underpricing is saved as text , so changing it to double 
with engine.begin() as conn:
    conn.execute(text("ALTER TABLE ipos MODIFY underpricing DOUBLE"))

In [32]:
# top 5 biggest issuers
run("""
SELECT ipo_name, issue_size
FROM ipos
ORDER BY issue_size DESC
LIMIT 5;
"""
)

                                    ipo_name  issue_size
0  Life Insurance Corporation of India (LIC)     20557.2
1                         Vodafone Idea Ltd      18000.0
2                             Coal India Ltd     15199.4
3                               Yes Bank Ltd     15000.0
4             HDB Financial Services Limited     12500.0

In [33]:
#IPOs per year, with average underpricing:
run("""SELECT YEAR(date) AS yr, COUNT(*) AS n, ROUND(AVG(underpricing), 2) AS avg_underpricing
FROM ipos GROUP BY yr ORDER BY yr;""")

      yr   n  avg_underpricing
0   2010  72             10.08
1   2011  39              3.18
2   2012  10              2.41
3   2013   4              4.50
4   2014   6             25.13
5   2015  18              5.78
6   2016  26             11.48
7   2017  34             20.68
8   2018  19              1.32
9   2019  16             14.16
10  2020  13             44.01
11  2021  47             24.45
12  2022  39             10.25
13  2023  54             22.23
14  2024  75             27.40
15  2025  37             10.19

In [34]:
run("""SELECT underpricing_class, COUNT(*) AS n, MIN(underpricing) AS lowest, MAX(underpricing) AS highest
FROM ipos GROUP BY underpricing_class;""")

  underpricing_class    n     lowest     highest
0                Low  300 -31.734694   10.000000
1             Medium  107  10.000000   29.333333
2               High  102  30.363636  252.760736

In [35]:
#Subscription tiers 
run("""SELECT CASE WHEN total < 2.98 THEN 'Low'
            WHEN total < 30.63 THEN 'Medium'
            ELSE 'High' END AS sub_group,
       COUNT(*) AS n, ROUND(AVG(underpricing), 2) AS avg_underpricing
FROM ipos GROUP BY sub_group;""")

  sub_group    n  avg_underpricing
0       Low  170             -0.83
1    Medium  169              7.39
2      High  170             41.45

In [36]:
#Years with more than 20 IPOs (HAVING filters groups, while WHERE filters rows):
run("""SELECT YEAR(date) AS yr, COUNT(*) AS n FROM ipos GROUP BY yr HAVING COUNT(*) > 20;""")

     yr   n
0  2010  72
1  2011  39
2  2016  26
3  2017  34
4  2021  47
5  2022  39
6  2023  54
7  2024  75
8  2025  37

In [37]:
#Ranking all IPOs by underpricing within each year, using RANK(), and show the top 3 per year.

run("""
WITH ranked AS (
    SELECT YEAR(date) AS yr, ipo_name, underpricing,
           RANK() OVER (PARTITION BY YEAR(date) ORDER BY underpricing DESC) AS rnk
    FROM ipos
)
SELECT yr, ipo_name, underpricing
FROM ranked
WHERE rnk <= 3
ORDER BY yr, rnk;
""")

      yr                                           ipo_name  underpricing
0   2010                                  Gravita India Ltd     75.000000
1   2010           DQ Entertainment (International) Limited     68.750000
2   2010                                     CP Capital Ltd     48.709677
3   2011                         AcroPetal Technologies Ltd     44.444444
4   2011                               Lovable Lingerie Ltd     27.560976
5   2011                              Fineotex Chemical Ltd     14.285714
6   2011                                    Timbor Home Ltd     14.285714
7   2012                                   CARE Ratings Ltd     26.533333
8   2012                                     MT Educare Ltd      7.562500
9   2012                                    Tara Jewels Ltd      5.217391
10  2013                                      Just Dial Ltd     11.320755
11  2013                Power Grid Corporation of India Ltd      7.888889
12  2013                                  V-Mart Retail Ltd      2.857143
13  2014                                Sharda Cropchem Ltd     62.884615
14  2014                              Snowman Logistics Ltd     59.574468
15  2014                              Wonderla Holidays Ltd     31.800000
16  2015                                  VRL Logistics Ltd     40.487805
17  2015                                Dr Lal Pathlabs Ltd     30.363636
18  2015                           S H Kelkar & Company Ltd     23.333333
19  2016                                     Quess Corp Ltd     57.413249
20  2016                         Thyrocare Technologies Ltd     48.430493
21  2016                               Equitas Holdings Ltd     30.909091
22  2017                     Salasar Techno Engineering Ltd    139.953704
23  2017                      Astron Paper & Board Mill Ltd    128.000000
24  2017                      Avenue Supermarts Ltd (DMart)    102.140468
25  2018                           Apollo Micro Systems Ltd     73.818182
26  2018                                   Bandhan Bank Ltd     29.333333
27  2018                              Lemon Tree Hotels Ltd     10.000000
28  2019  Indian Railway Catering and Tourism Corporatio...    101.250000
29  2019                     Ujjivan Small Finance Bank Ltd     56.756757
30  2019                                       CSB Bank Ltd     41.025641
31  2020                   Chemcon Speciality Chemicals Ltd    114.985294
32  2020                    Happiest Minds Technologies Ltd    111.445783
33  2020                                   Route Mobile Ltd    102.285714
34  2021                         Sigachi Industries Limited    252.760736
35  2021       Paras Defence and Space Technologies Limited    171.428571
36  2021                              Latent View Analytics    169.035533
37  2022                                Dreamfolks Services     54.907975
38  2022                             Electronics Mart India     51.525424
39  2022                     Hariom Pipe Industries Limited     39.869281
40  2023                         Motisons Jewellers Limited     88.909091
41  2023                  Netweb Technologies India Limited     88.500000
42  2023                        Aeroflex Industries Limited     82.777778
43  2024                         Vibhor Steel Tubes Limited    178.807947
44  2024                           Mamata Machinery Limited    146.913580
45  2024                             BLS E-Services Limited    128.888889
46  2025                            GNG Electronics Limited     47.679325
47  2025                         Sambhv Steel Tubes Limited     34.268293
48  2025                  Stallion India Fluorochem Limited     33.333333

In [38]:
#Show each IPO’s issue size next to the average issue size of its year, using AVG() OVER (PARTITION BY ...), and the difference. 
run("""
WITH AVG_SIZE AS ( SELECT YEAR(DATE) AS YR  ,IPO_NAME ,  ISSUE_SIZE , AVG(ISSUE_SIZE) OVER ( PARTITION BY YEAR(DATE)) AS AVG_THAT_YEAR FROM ipos )
SELECT YR , IPO_NAME ,  ISSUE_SIZE , AVG_THAT_YEAR , (ISSUE_SIZE - AVG_THAT_YEAR) AS DIFF FROM AVG_SIZE ORDER BY YR ;
""" )

,YR,IPO_NAME,ISSUE_SIZE,AVG_THAT_YEAR,DIFF
0,2010,JSW Energy Limited,2700.00,1012.897361,1687.102639
1,2010,Godrej Properties Limited,468.85,1012.897361,-544.047361
2,2010,D B Corp Limited,384.22,1012.897361,-628.677361
3,2010,MBL Infrastructure Limited,102.60,1012.897361,-910.297361
4,2010,Birla Shloka Edutech Limited,34.78,1012.897361,-978.117361
...,...,...,...,...,...
504,2025,Shanti Gold International Ltd,360.11,1622.669730,-1262.559730
505,2025,Laxmi India Finance Ltd,254.26,1622.669730,-1368.409730
506,2025,National Securities Depository Ltd (NSDL),4011.60,1622.669730,2388.930270
507,2025,Sri Lotus Developers & Realty Ltd,792.00,1622.669730,-830.669730
508,2025,M & B Engineering Ltd,650.00,1622.669730,-972.669730

In [39]:
#For each IPO, show the previous IPO’s underpricing (ordered by date) using LAG, and flag rows where underpricing rose.


run("""
SELECT date,
       ipo_name,
       underpricing,
       LAG(underpricing) OVER (ORDER BY date, ipo_name) AS prev_underpricing,
       CASE
           WHEN LAG(underpricing) OVER (ORDER BY date, ipo_name) IS NULL THEN 'n/a'
           WHEN underpricing > LAG(underpricing) OVER (ORDER BY date, ipo_name) THEN 'Rose'
           ELSE 'Did not rise'
       END AS trend
FROM ipos
ORDER BY date, ipo_name;
""")

,date,ipo_name,underpricing,prev_underpricing,trend
0,2010-01-04,JSW Energy Limited,2.000000,NaN,n/a
1,2010-01-05,Godrej Properties Limited,4.081633,2.000000,Rose
2,2010-01-06,D B Corp Limited,17.924528,4.081633,Rose
3,2010-01-11,MBL Infrastructure Limited,5.555556,17.924528,Did not rise
4,2010-01-29,Birla Shloka Edutech Limited,-2.000000,5.555556,Did not rise
...,...,...,...,...,...
504,2025-08-01,Shanti Gold International Ltd,15.125628,-8.888889,Rose
505,2025-08-05,Laxmi India Finance Ltd,-13.924051,15.125628,Did not rise
506,2025-08-06,M & B Engineering Ltd,0.259740,-13.924051,Rose
507,2025-08-06,National Securities Depository Ltd (NSDL),10.000000,0.259740,Rose
508,2025-08-06,Sri Lotus Developers & Realty Ltd,19.400000,10.000000,Rose

In [40]:
#Calculate a 5-IPO moving average of underpricing, ordered by date.
run("""
SELECT date,
       ipo_name,
       underpricing,
       ROUND(AVG(underpricing) OVER (
           ORDER BY date, ipo_name 
           ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
       ), 2) AS moving_avg_5
FROM ipos
ORDER BY date, ipo_name;
""")

,date,ipo_name,underpricing,moving_avg_5
0,2010-01-04,JSW Energy Limited,2.000000,2.00
1,2010-01-05,Godrej Properties Limited,4.081633,3.04
2,2010-01-06,D B Corp Limited,17.924528,8.00
3,2010-01-11,MBL Infrastructure Limited,5.555556,7.39
4,2010-01-29,Birla Shloka Edutech Limited,-2.000000,5.51
...,...,...,...,...
504,2025-08-01,Shanti Gold International Ltd,15.125628,14.61
505,2025-08-05,Laxmi India Finance Ltd,-13.924051,6.45
506,2025-08-06,M & B Engineering Ltd,0.259740,-3.03
507,2025-08-06,National Securities Depository Ltd (NSDL),10.000000,0.51
508,2025-08-06,Sri Lotus Developers & Realty Ltd,19.400000,6.17

In [41]:
#Show the best and worst IPO of each year in one result, with FIRST_VALUE or ROW_NUMBER.
run("""
SELECT DISTINCT
       yr,
       FIRST_VALUE(ipo_name)     OVER (PARTITION BY yr ORDER BY underpricing DESC, ipo_name) AS best_ipo,
       FIRST_VALUE(underpricing) OVER (PARTITION BY yr ORDER BY underpricing DESC, ipo_name) AS best_underpricing,
       FIRST_VALUE(ipo_name)     OVER (PARTITION BY yr ORDER BY underpricing ASC, ipo_name)  AS worst_ipo,
       FIRST_VALUE(underpricing) OVER (PARTITION BY yr ORDER BY underpricing ASC, ipo_name)  AS worst_underpricing
FROM (SELECT YEAR(date) AS yr, ipo_name, underpricing FROM ipos) t
ORDER BY yr;
""")

,yr,best_ipo,best_underpricing,worst_ipo,worst_underpricing
0,2010,Gravita India Ltd,75.000000,Jaypee Infratech Limited,-8.823529
1,2011,AcroPetal Technologies Ltd,44.444444,Vaswani Industries Ltd,-31.734694
2,2012,CARE Ratings Ltd,26.533333,Indus Towers Ltd,-9.090909
3,2013,Just Dial Ltd,11.320755,Repco Home Finance Ltd,-4.069767
4,2014,Sharda Cropchem Ltd,62.884615,Monte Carlo Fashions Ltd,-9.302326
5,2015,VRL Logistics Ltd,40.487805,Pennar Engineered Building Systems Ltd,-15.730337
6,2016,Quess Corp Ltd,57.413249,Precision Camshafts Ltd,-12.311828
7,2017,Salasar Techno Engineering Ltd,139.953704,CL Educate Ltd,-20.717131
8,2018,Apollo Micro Systems Ltd,73.818182,Dharan Infra EPC Ltd,-24.444444
9,2019,Indian Railway Catering and Tourism Corporatio...,101.250000,Xelpmoc Design and Technologies Ltd,-15.151515
10,2020,Chemcon Speciality Chemicals Ltd,114.985294,SBI Cards & Payment Services Ltd,-12.847682
11,2021,Sigachi Industries Limited,252.760736,Shriram Properties Limited,-20.338983
12,2022,Dreamfolks Services,54.907975,Life Insurance Corporation of India (LIC),-8.619600
13,2023,Motisons Jewellers Limited,88.909091,Yatra Online Limited,-8.450704
14,2024,Vibhor Steel Tubes Limited,178.807947,Gopal Snacks Ltd,-12.718204
15,2025,GNG Electronics Limited,47.679325,Laxmi India Finance Ltd,-13.924051

In [42]:
#Split the IPOs into 4 groups by total using NTILE(4), then compute the average underpricing per group.
run("""
WITH grouped AS (
    SELECT underpricing,
           total,
           NTILE(4) OVER (ORDER BY total) AS quartile
    FROM ipos
)
SELECT quartile,
       COUNT(*)                        AS n,
       MIN(total)                      AS min_total,
       MAX(total)                      AS max_total,
       ROUND(AVG(underpricing), 2)     AS avg_underpricing
FROM grouped
GROUP BY quartile
ORDER BY quartile;
""")

   quartile    n  min_total  max_total  avg_underpricing
0         1  128       0.11       2.20             -0.91
1         2  127       2.21       8.77              2.43
2         3  127       8.99      46.68             13.84
3         4  127      47.19     326.49             48.84

In [43]:
run("DESCRIBE ipos")

                 Field      Type Null Key Default Extra
0                 date  datetime  YES        None
1             ipo_name      text  YES        None
2           issue_size    double  YES        None
3          offer_price    double  YES        None
4                  qib    double  YES        None
5                  hni    double  YES        None
6                  rii    double  YES        None
7                total    double  YES        None
8     nifty_20d_return    double  YES        None
9     nifty_60d_return    double  YES        None
10           india_vix    double  YES        None
11        underpricing    double  YES        None
12  underpricing_class      text  YES        None